server:
  port: 8080

mybatis-plus:
  type-aliases-package: cn.edu.zsc.study.entity
  mapper-locations: classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&characterEncoding=utf8&serverTimezone=Hongkong
    username: root
    password: 2002
    driver-class-name: com.mysql.cj.jdbc.Driver